GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMwLCJuYW1lIjoiWWF6aWQiLCJlbWFpbCI6ImdoYW5pQGdtYWlsLmNvbSIsImlhdCI6MTcwMjk0ODcwMSwiZXhwIjoxNzAyOTQ4NzYxfQ.XbrNqY_oBMRhDP8jBYL-cA_wA1NSJdYHgw6oH1bVZhQ
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name" : "Yazid",
    "email" : "ghani@gmail.com",
    "password" : "abcdef",
    "confPassword" : "abcdef"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "ghani@gmail.com",
    "password" : "abcdef"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout
